---

# PySpark DataFrame Exercises Lab

Students will work with 4 datasets.

1. `employees.csv`
2. `departments.csv`
3. `sales.csv`
4. `employees_nested.json`

---

## Dataset 1 — employees.csv

Students should create this file.

```csv
emp_id,name,department,salary,joining_date
1,Rahul,IT,70000,2023-01-10
2,Sneha,HR,60000,2022-11-15
3,Arjun,IT,75000,2023-03-01
4,Priya,Finance,80000,2022-12-20
5,Karan,IT,50000,2023-02-05
6,Meera,,72000,2023-04-10
7,Amit,HR,58000,2023-01-18
```

---

## Dataset 2 — departments.csv

```csv
department,location
IT,Bangalore
HR,Mumbai
Finance,Delhi
```

---

## Dataset 3 — sales.csv

```csv
sale_id,emp_id,product,amount
1,1,Laptop,75000
2,2,Mouse,1500
3,3,Keyboard,3000
4,1,Monitor,12000
5,4,Laptop,75000
6,3,Mouse,1000
7,5,Keyboard,1500
8,1,Laptop,75000
```

---

## Dataset 4 — employees_nested.json

```json
[
 {
  "emp_id":1,
  "name":"Rahul",
  "address":{"city":"Hyderabad","state":"Telangana"},
  "skills":["Python","SQL"]
 },
 {
  "emp_id":2,
  "name":"Sneha",
  "address":{"city":"Bangalore","state":"Karnataka"},
  "skills":["HR","Recruitment"]
 },
 {
  "emp_id":3,
  "name":"Arjun",
  "address":{"city":"Chennai","state":"Tamil Nadu"},
  "skills":["PySpark","Azure","Python"]
 }
]
```

In [57]:
from google.colab import files
uploaded=files.upload()

Saving departments.csv to departments (1).csv
Saving employees.csv to employees (1).csv
Saving employees_nested.json to employees_nested (1).json
Saving sales.csv to sales (1).csv

In [58]:
!ls

'departments (1).csv'   employees.csv		    'sales (1).csv'
 departments.csv       'employees_nested (1).json'   sales.csv
'employees (1).csv'     employees_nested.json	     sample_data

---

# PART 1 — DataFrame Creation

Exercise 1  
Create a Spark session.

Exercise 2  
Load employees.csv.

Exercise 3  
Load departments.csv.

Exercise 4  
Load sales.csv.

Exercise 5  
Load employees_nested.json.

Exercise 6  
Print schema for all DataFrames.

---

In [59]:
from pyspark.sql import SparkSession
spark=SparkSession.builder.appName("PySpark DataFrame Exercises").getOrCreate()

In [99]:
df_employees=spark.read.csv("employees.csv",header=True,inferSchema=True)
df_departments=spark.read.csv("departments.csv",header=True,inferSchema=True)
df_sales=spark.read.csv("sales.csv",header=True,inferSchema=True)
df_employees_nested=spark.read.option("multiline", "true").json("employees_nested.json")

In [98]:
df_employees.show()
df_departments.show()
df_employees_nested.show(truncate=False)
df_sales.show()

+------+-----+----------+----------+
|emp_id| name|department|emp_salary|
+------+-----+----------+----------+
|     1|Rahul|        IT|     70000|
|     2|Sneha|        HR|     60000|
|     3|Arjun|        IT|     75000|
|     4|Priya|   Finance|     80000|
|     5|Karan|        IT|     50000|
|     6|Meera|      NULL|     72000|
|     7| Amit|        HR|     58000|
+------+-----+----------+----------+

+----------+---------+
|department| location|
+----------+---------+
|        IT|Bangalore|
|        HR|   Mumbai|
|   Finance|    Delhi|
+----------+---------+

+----------------------+------+-----+------------------------+
|address               |emp_id|name |skills                  |
+----------------------+------+-----+------------------------+
|{Hyderabad, Telangana}|1     |Rahul|[Python, SQL]           |
|{Bangalore, Karnataka}|2     |Sneha|[HR, Recruitment]       |
|{Chennai, Tamil Nadu} |3     |Arjun|[PySpark, Azure, Python]|
+----------------------+------+-----+------------------------+

+-------+------+--------+------+
|sale_id|emp_id| product|amount|
+-------+------+--------+------+
|      1|     1|  Laptop| 75000|
|      2|     2|   Mouse|  1500|
|      3|     3|Keyboard|  3000|
|      4|     1| Monitor| 12000|
|      5|     4|  Laptop| 75000|
|      6|     3|   Mouse|  1000|
|      7|     5|Keyboard|  1500|
|      8|     1|  Laptop| 75000|
+-------+------+--------+------+

In [62]:
df_employees.printSchema()
df_departments.printSchema()
df_sales.printSchema()
df_employees_nested.printSchema()

root
 |-- emp_id: integer (nullable = true)
 |-- name: string (nullable = true)
 |-- department: string (nullable = true)
 |-- salary: integer (nullable = true)
 |-- joining_date: date (nullable = true)

root
 |-- department: string (nullable = true)
 |-- location: string (nullable = true)

root
 |-- sale_id: integer (nullable = true)
 |-- emp_id: integer (nullable = true)
 |-- product: string (nullable = true)
 |-- amount: integer (nullable = true)

root
 |-- address: struct (nullable = true)
 |    |-- city: string (nullable = true)
 |    |-- state: string (nullable = true)
 |-- emp_id: long (nullable = true)
 |-- name: string (nullable = true)
 |-- skills: array (nullable = true)
 |    |-- element: string (containsNull = true)

---

# PART 2 — Exploring Data

Exercise 7  
Show first 5 rows of employees.

Exercise 8  
Count total employees.

Exercise 9  
List all column names.

Exercise 10  
Show only 3 rows.

---

In [63]:
df_employees.show(5)

+------+-----+----------+------+------------+
|emp_id| name|department|salary|joining_date|
+------+-----+----------+------+------------+
|     1|Rahul|        IT| 70000|  2023-01-10|
|     2|Sneha|        HR| 60000|  2022-11-15|
|     3|Arjun|        IT| 75000|  2023-03-01|
|     4|Priya|   Finance| 80000|  2022-12-20|
|     5|Karan|        IT| 50000|  2023-02-05|
+------+-----+----------+------+------------+
only showing top 5 rows

In [64]:
df_employees.count()

7

In [65]:
df_employees.columns

['emp_id', 'name', 'department', 'salary', 'joining_date']

In [66]:
df_employees.show(3)

+------+-----+----------+------+------------+
|emp_id| name|department|salary|joining_date|
+------+-----+----------+------+------------+
|     1|Rahul|        IT| 70000|  2023-01-10|
|     2|Sneha|        HR| 60000|  2022-11-15|
|     3|Arjun|        IT| 75000|  2023-03-01|
+------+-----+----------+------+------------+
only showing top 3 rows

---

# PART 3 — Selecting and Renaming

Exercise 11  
Select only:  
name  
salary  

Exercise 12  
Rename column salary to emp_salary.

Exercise 13  
Select employees who joined after 2023-01-01.

---

In [67]:
df_employees.select("name","salary").show()

+-----+------+
| name|salary|
+-----+------+
|Rahul| 70000|
|Sneha| 60000|
|Arjun| 75000|
|Priya| 80000|
|Karan| 50000|
|Meera| 72000|
| Amit| 58000|
+-----+------+

In [68]:
df_employees=df_employees.withColumnRenamed("salary","emp_salary")
df_employees.show()

+------+-----+----------+----------+------------+
|emp_id| name|department|emp_salary|joining_date|
+------+-----+----------+----------+------------+
|     1|Rahul|        IT|     70000|  2023-01-10|
|     2|Sneha|        HR|     60000|  2022-11-15|
|     3|Arjun|        IT|     75000|  2023-03-01|
|     4|Priya|   Finance|     80000|  2022-12-20|
|     5|Karan|        IT|     50000|  2023-02-05|
|     6|Meera|      NULL|     72000|  2023-04-10|
|     7| Amit|        HR|     58000|  2023-01-18|
+------+-----+----------+----------+------------+

In [69]:
df_employees.filter(df_employees.joining_date>"2023-01-01").show()

+------+-----+----------+----------+------------+
|emp_id| name|department|emp_salary|joining_date|
+------+-----+----------+----------+------------+
|     1|Rahul|        IT|     70000|  2023-01-10|
|     3|Arjun|        IT|     75000|  2023-03-01|
|     5|Karan|        IT|     50000|  2023-02-05|
|     6|Meera|      NULL|     72000|  2023-04-10|
|     7| Amit|        HR|     58000|  2023-01-18|
+------+-----+----------+----------+------------+

# PART 4 — Filtering Data

Exercise 14  
Find employees with salary greater than 65000.

Exercise 15  
Find employees in IT department.

Exercise 16  
Find employees in IT department with salary greater than 70000.

---

In [70]:
df_employees.filter(df_employees.emp_salary>65000).show()

+------+-----+----------+----------+------------+
|emp_id| name|department|emp_salary|joining_date|
+------+-----+----------+----------+------------+
|     1|Rahul|        IT|     70000|  2023-01-10|
|     3|Arjun|        IT|     75000|  2023-03-01|
|     4|Priya|   Finance|     80000|  2022-12-20|
|     6|Meera|      NULL|     72000|  2023-04-10|
+------+-----+----------+----------+------------+

In [71]:
df_employees.filter(df_employees.department=="IT").show()

+------+-----+----------+----------+------------+
|emp_id| name|department|emp_salary|joining_date|
+------+-----+----------+----------+------------+
|     1|Rahul|        IT|     70000|  2023-01-10|
|     3|Arjun|        IT|     75000|  2023-03-01|
|     5|Karan|        IT|     50000|  2023-02-05|
+------+-----+----------+----------+------------+

In [72]:
df_employees.filter((df_employees.department=="IT")&(df_employees.emp_salary>70000)).show()

+------+-----+----------+----------+------------+
|emp_id| name|department|emp_salary|joining_date|
+------+-----+----------+----------+------------+
|     3|Arjun|        IT|     75000|  2023-03-01|
+------+-----+----------+----------+------------+

---

# PART 5 — Dropping and Sorting

Exercise 17  
Drop column joining_date.

Exercise 18  
Sort employees by salary ascending.

Exercise 19  
Sort employees by salary descending.

Exercise 20  
Find top 3 highest paid employees.

---

In [73]:
df_employees=df_employees.drop("joining_date")
df_employees.show()

+------+-----+----------+----------+
|emp_id| name|department|emp_salary|
+------+-----+----------+----------+
|     1|Rahul|        IT|     70000|
|     2|Sneha|        HR|     60000|
|     3|Arjun|        IT|     75000|
|     4|Priya|   Finance|     80000|
|     5|Karan|        IT|     50000|
|     6|Meera|      NULL|     72000|
|     7| Amit|        HR|     58000|
+------+-----+----------+----------+

In [74]:
df_employees.sort(df_employees.emp_salary).show()

+------+-----+----------+----------+
|emp_id| name|department|emp_salary|
+------+-----+----------+----------+
|     5|Karan|        IT|     50000|
|     7| Amit|        HR|     58000|
|     2|Sneha|        HR|     60000|
|     1|Rahul|        IT|     70000|
|     6|Meera|      NULL|     72000|
|     3|Arjun|        IT|     75000|
|     4|Priya|   Finance|     80000|
+------+-----+----------+----------+

In [75]:
df_employees.sort(df_employees.emp_salary.desc()).show()

+------+-----+----------+----------+
|emp_id| name|department|emp_salary|
+------+-----+----------+----------+
|     4|Priya|   Finance|     80000|
|     3|Arjun|        IT|     75000|
|     6|Meera|      NULL|     72000|
|     1|Rahul|        IT|     70000|
|     2|Sneha|        HR|     60000|
|     7| Amit|        HR|     58000|
|     5|Karan|        IT|     50000|
+------+-----+----------+----------+

In [76]:
df_employees.sort(df_employees.emp_salary.desc()).show(3)

+------+-----+----------+----------+
|emp_id| name|department|emp_salary|
+------+-----+----------+----------+
|     4|Priya|   Finance|     80000|
|     3|Arjun|        IT|     75000|
|     6|Meera|      NULL|     72000|
+------+-----+----------+----------+
only showing top 3 rows

---

# PART 6 — Aggregations

Exercise 21  
Find total salary of all employees.

Exercise 22  
Find average salary.

Exercise 23  
Find highest salary.

Exercise 24  
Find lowest salary.

---

In [77]:
from pyspark.sql.functions import sum,avg,min,max
df_employees.select(sum("emp_salary").alias("TotalSalary")).show()

+-----------+
|TotalSalary|
+-----------+
|     465000|
+-----------+

In [78]:
df_employees.select(avg("emp_salary").alias("AverageSalary")).show()

+-----------------+
|    AverageSalary|
+-----------------+
|66428.57142857143|
+-----------------+

In [79]:
df_employees.select(max("emp_salary").alias("HighestSalary")).show()

+-------------+
|HighestSalary|
+-------------+
|        80000|
+-------------+

In [80]:
df_employees.select(min("emp_salary").alias("LowestSalary")).show()

+------------+
|LowestSalary|
+------------+
|       50000|
+------------+

---

# PART 7 — GroupBy

Exercise 25  
Count employees per department.

Exercise 26  
Calculate average salary per department.

Exercise 27  
Find total salary per department.

---

In [81]:
df_employees.groupBy("department").count().show()

+----------+-----+
|department|count|
+----------+-----+
|        HR|    2|
|      NULL|    1|
|   Finance|    1|
|        IT|    3|
+----------+-----+

In [82]:
df_employees.groupBy("department").avg("emp_salary").show()

+----------+---------------+
|department|avg(emp_salary)|
+----------+---------------+
|        HR|        59000.0|
|      NULL|        72000.0|
|   Finance|        80000.0|
|        IT|        65000.0|
+----------+---------------+

In [83]:
df_employees.groupBy("department").sum("emp_salary").show()

+----------+---------------+
|department|sum(emp_salary)|
+----------+---------------+
|        HR|         118000|
|      NULL|          72000|
|   Finance|          80000|
|        IT|         195000|
+----------+---------------+

---

# PART 8 — Joining DataFrames

Use employees.csv and departments.csv.

Exercise 28  
Perform inner join.

Exercise 29  
Perform left join.

Exercise 30  
Show employee name with department location.

---

In [84]:
df_employees.join(df_departments,df_employees.department==df_departments.department,"inner").show()

+------+-----+----------+----------+----------+---------+
|emp_id| name|department|emp_salary|department| location|
+------+-----+----------+----------+----------+---------+
|     1|Rahul|        IT|     70000|        IT|Bangalore|
|     2|Sneha|        HR|     60000|        HR|   Mumbai|
|     3|Arjun|        IT|     75000|        IT|Bangalore|
|     4|Priya|   Finance|     80000|   Finance|    Delhi|
|     5|Karan|        IT|     50000|        IT|Bangalore|
|     7| Amit|        HR|     58000|        HR|   Mumbai|
+------+-----+----------+----------+----------+---------+

In [85]:
df_employees.join(df_departments,df_employees.department==df_departments.department,"left").show()

+------+-----+----------+----------+----------+---------+
|emp_id| name|department|emp_salary|department| location|
+------+-----+----------+----------+----------+---------+
|     1|Rahul|        IT|     70000|        IT|Bangalore|
|     2|Sneha|        HR|     60000|        HR|   Mumbai|
|     3|Arjun|        IT|     75000|        IT|Bangalore|
|     4|Priya|   Finance|     80000|   Finance|    Delhi|
|     5|Karan|        IT|     50000|        IT|Bangalore|
|     6|Meera|      NULL|     72000|      NULL|     NULL|
|     7| Amit|        HR|     58000|        HR|   Mumbai|
+------+-----+----------+----------+----------+---------+

In [86]:
df_employees.join(df_departments,df_employees.department==df_departments.department,"inner").select("name","location").show()

+-----+---------+
| name| location|
+-----+---------+
|Rahul|Bangalore|
|Sneha|   Mumbai|
|Arjun|Bangalore|
|Priya|    Delhi|
|Karan|Bangalore|
| Amit|   Mumbai|
+-----+---------+

---

# PART 9 — Updating Data

Exercise 31  
Add a column bonus = salary * 10%.

Exercise 32  
Add a column company with value "BotCampus".

---

In [87]:
df_employees.withColumn("bonus",df_employees.emp_salary*0.1).show()

+------+-----+----------+----------+------+
|emp_id| name|department|emp_salary| bonus|
+------+-----+----------+----------+------+
|     1|Rahul|        IT|     70000|7000.0|
|     2|Sneha|        HR|     60000|6000.0|
|     3|Arjun|        IT|     75000|7500.0|
|     4|Priya|   Finance|     80000|8000.0|
|     5|Karan|        IT|     50000|5000.0|
|     6|Meera|      NULL|     72000|7200.0|
|     7| Amit|        HR|     58000|5800.0|
+------+-----+----------+----------+------+

In [88]:
from pyspark.sql.functions import lit

In [89]:
df_employees.withColumn("company",lit("BotCampus")).show()
#

+------+-----+----------+----------+---------+
|emp_id| name|department|emp_salary|  company|
+------+-----+----------+----------+---------+
|     1|Rahul|        IT|     70000|BotCampus|
|     2|Sneha|        HR|     60000|BotCampus|
|     3|Arjun|        IT|     75000|BotCampus|
|     4|Priya|   Finance|     80000|BotCampus|
|     5|Karan|        IT|     50000|BotCampus|
|     6|Meera|      NULL|     72000|BotCampus|
|     7| Amit|        HR|     58000|BotCampus|
+------+-----+----------+----------+---------+

---

# PART 10 — Handling Null Values

Note employee Meera has null department.

Exercise 33  
Find rows with null department.

Exercise 34  
Replace null department with "Unknown".

Exercise 35  
Drop rows with null values.

---

In [90]:
from pyspark.sql.functions import col
df_employees.filter(col("department").isNull()).show()

+------+-----+----------+----------+
|emp_id| name|department|emp_salary|
+------+-----+----------+----------+
|     6|Meera|      NULL|     72000|
+------+-----+----------+----------+

In [91]:
df_employees.na.fill({"department":"Unknown"}).show()

+------+-----+----------+----------+
|emp_id| name|department|emp_salary|
+------+-----+----------+----------+
|     1|Rahul|        IT|     70000|
|     2|Sneha|        HR|     60000|
|     3|Arjun|        IT|     75000|
|     4|Priya|   Finance|     80000|
|     5|Karan|        IT|     50000|
|     6|Meera|   Unknown|     72000|
|     7| Amit|        HR|     58000|
+------+-----+----------+----------+

In [92]:
df_employees.na.drop().show()

+------+-----+----------+----------+
|emp_id| name|department|emp_salary|
+------+-----+----------+----------+
|     1|Rahul|        IT|     70000|
|     2|Sneha|        HR|     60000|
|     3|Arjun|        IT|     75000|
|     4|Priya|   Finance|     80000|
|     5|Karan|        IT|     50000|
|     7| Amit|        HR|     58000|
+------+-----+----------+----------+

---

# PART 11 — Built-in Functions

Exercise 36  
Convert employee names to uppercase.

Exercise 37  
Find length of employee names.

Exercise 38  
Create column salary_in_lakhs.

---

In [93]:
from pyspark.sql.functions import length,upper
df_employees.select(df_employees.name,upper(df_employees.name).alias("UpperCase Name")).show()

+-----+--------------+
| name|UpperCase Name|
+-----+--------------+
|Rahul|         RAHUL|
|Sneha|         SNEHA|
|Arjun|         ARJUN|
|Priya|         PRIYA|
|Karan|         KARAN|
|Meera|         MEERA|
| Amit|          AMIT|
+-----+--------------+

In [94]:
df_employees.select("name",length(df_employees.name).alias("Length of Name")).show()

+-----+--------------+
| name|Length of Name|
+-----+--------------+
|Rahul|             5|
|Sneha|             5|
|Arjun|             5|
|Priya|             5|
|Karan|             5|
|Meera|             5|
| Amit|             4|
+-----+--------------+

In [95]:
df_employees.withColumn("salary_in_lakhs",df_employees.emp_salary/100000).show()

+------+-----+----------+----------+---------------+
|emp_id| name|department|emp_salary|salary_in_lakhs|
+------+-----+----------+----------+---------------+
|     1|Rahul|        IT|     70000|            0.7|
|     2|Sneha|        HR|     60000|            0.6|
|     3|Arjun|        IT|     75000|           0.75|
|     4|Priya|   Finance|     80000|            0.8|
|     5|Karan|        IT|     50000|            0.5|
|     6|Meera|      NULL|     72000|           0.72|
|     7| Amit|        HR|     58000|           0.58|
+------+-----+----------+----------+---------------+

---

# PART 12 — When / Otherwise

Create salary category:

>= 75000 → High  
60000–74999 → Medium  
< 60000 → Low  

Exercise 39  
Create new column salary_grade.

---

In [96]:
from pyspark.sql.functions import when
salary_category=when(df_employees.emp_salary>=75000,"High").when((df_employees.emp_salary>=60000)&(df_employees.emp_salary<=74999),"Medium").otherwise("Low")
df_employees.withColumn("salary_grade",salary_category).show()

+------+-----+----------+----------+------------+
|emp_id| name|department|emp_salary|salary_grade|
+------+-----+----------+----------+------------+
|     1|Rahul|        IT|     70000|      Medium|
|     2|Sneha|        HR|     60000|      Medium|
|     3|Arjun|        IT|     75000|        High|
|     4|Priya|   Finance|     80000|        High|
|     5|Karan|        IT|     50000|         Low|
|     6|Meera|      NULL|     72000|      Medium|
|     7| Amit|        HR|     58000|         Low|
+------+-----+----------+----------+------------+

---

# PART 13 — Date Functions

Exercise 40  
Convert joining_date to proper date format.

Exercise 41  
Extract:  
joining year  
joining month  

---

In [100]:
from pyspark.sql.functions import to_date,year,month
df_employees.withColumn("joining_date",to_date(df_employees.joining_date)).show()

+------+-----+----------+------+------------+
|emp_id| name|department|salary|joining_date|
+------+-----+----------+------+------------+
|     1|Rahul|        IT| 70000|  2023-01-10|
|     2|Sneha|        HR| 60000|  2022-11-15|
|     3|Arjun|        IT| 75000|  2023-03-01|
|     4|Priya|   Finance| 80000|  2022-12-20|
|     5|Karan|        IT| 50000|  2023-02-05|
|     6|Meera|      NULL| 72000|  2023-04-10|
|     7| Amit|        HR| 58000|  2023-01-18|
+------+-----+----------+------+------------+

In [101]:
df_employees.select("joining_date",year(df_employees.joining_date).alias("joining_year"),month(df_employees.joining_date).alias("joining_month")).show()

+------------+------------+-------------+
|joining_date|joining_year|joining_month|
+------------+------------+-------------+
|  2023-01-10|        2023|            1|
|  2022-11-15|        2022|           11|
|  2023-03-01|        2023|            3|
|  2022-12-20|        2022|           12|
|  2023-02-05|        2023|            2|
|  2023-04-10|        2023|            4|
|  2023-01-18|        2023|            1|
+------------+------------+-------------+

---

# PART 14 — Union

Create another DataFrame with 2 new employees.

Exercise 42  
Union the two DataFrames.

Exercise 43  
Use unionByName.

---

In [102]:
new_employees=[
    ( 8,"Ray","HR",52000,"2023-10-10"),
    ( 9,"Preethi","IT",78000,"2023-07-18")
]
new_employees_df=spark.createDataFrame(new_employees,df_employees.columns)
new_employees_df.show()

+------+-------+----------+------+------------+
|emp_id|   name|department|salary|joining_date|
+------+-------+----------+------+------------+
|     8|    Ray|        HR| 52000|  2023-10-10|
|     9|Preethi|        IT| 78000|  2023-07-18|
+------+-------+----------+------+------------+

In [103]:
df_employees.union(new_employees_df).show()

+------+-------+----------+------+------------+
|emp_id|   name|department|salary|joining_date|
+------+-------+----------+------+------------+
|     1|  Rahul|        IT| 70000|  2023-01-10|
|     2|  Sneha|        HR| 60000|  2022-11-15|
|     3|  Arjun|        IT| 75000|  2023-03-01|
|     4|  Priya|   Finance| 80000|  2022-12-20|
|     5|  Karan|        IT| 50000|  2023-02-05|
|     6|  Meera|      NULL| 72000|  2023-04-10|
|     7|   Amit|        HR| 58000|  2023-01-18|
|     8|    Ray|        HR| 52000|  2023-10-10|
|     9|Preethi|        IT| 78000|  2023-07-18|
+------+-------+----------+------+------------+

In [104]:
df_employees.unionByName(new_employees_df).show()

+------+-------+----------+------+------------+
|emp_id|   name|department|salary|joining_date|
+------+-------+----------+------+------------+
|     1|  Rahul|        IT| 70000|  2023-01-10|
|     2|  Sneha|        HR| 60000|  2022-11-15|
|     3|  Arjun|        IT| 75000|  2023-03-01|
|     4|  Priya|   Finance| 80000|  2022-12-20|
|     5|  Karan|        IT| 50000|  2023-02-05|
|     6|  Meera|      NULL| 72000|  2023-04-10|
|     7|   Amit|        HR| 58000|  2023-01-18|
|     8|    Ray|        HR| 52000|  2023-10-10|
|     9|Preethi|        IT| 78000|  2023-07-18|
+------+-------+----------+------+------------+

---

# PART 15 — Window Functions

Exercise 44  
Rank employees by salary within department.

Exercise 45  
Assign row number within department.

---

In [105]:
from pyspark.sql.window import Window
from pyspark.sql.functions import rank,row_number

In [106]:
window = Window.partitionBy("department").orderBy(col("salary").desc())

df_employees.withColumn("rank", rank().over(window)).show()

df_employees.withColumn("row_number", row_number().over(window)).show()

+------+-----+----------+------+------------+----+
|emp_id| name|department|salary|joining_date|rank|
+------+-----+----------+------+------------+----+
|     6|Meera|      NULL| 72000|  2023-04-10|   1|
|     4|Priya|   Finance| 80000|  2022-12-20|   1|
|     2|Sneha|        HR| 60000|  2022-11-15|   1|
|     7| Amit|        HR| 58000|  2023-01-18|   2|
|     3|Arjun|        IT| 75000|  2023-03-01|   1|
|     1|Rahul|        IT| 70000|  2023-01-10|   2|
|     5|Karan|        IT| 50000|  2023-02-05|   3|
+------+-----+----------+------+------------+----+

+------+-----+----------+------+------------+----------+
|emp_id| name|department|salary|joining_date|row_number|
+------+-----+----------+------+------------+----------+
|     6|Meera|      NULL| 72000|  2023-04-10|         1|
|     4|Priya|   Finance| 80000|  2022-12-20|         1|
|     2|Sneha|        HR| 60000|  2022-11-15|         1|
|     7| Amit|        HR| 58000|  2023-01-18|         2|
|     3|Arjun|        IT| 75000|  2023-03-01|         1|
|     1|Rahul|        IT| 70000|  2023-01-10|         2|
|     5|Karan|        IT| 50000|  2023-02-05|         3|
+------+-----+----------+------+------------+----------+

---

# PART 16 — Working with Nested JSON

Exercise 46  
Read employees_nested.json.

Exercise 47  
Extract:  
emp_id  
city  
state  

Exercise 48  
Explode the skills array.

Expected output example:

Rahul → Python  
Rahul → SQL  

---

In [107]:
from pyspark.sql.functions import explode

In [108]:
df_employees_nested.select("emp_id","address.city","address.state").show()

+------+---------+----------+
|emp_id|     city|     state|
+------+---------+----------+
|     1|Hyderabad| Telangana|
|     2|Bangalore| Karnataka|
|     3|  Chennai|Tamil Nadu|
+------+---------+----------+

In [109]:
df_employees_nested.select("name", explode("skills")).show()

+-----+-----------+
| name|        col|
+-----+-----------+
|Rahul|     Python|
|Rahul|        SQL|
|Sneha|         HR|
|Sneha|Recruitment|
|Arjun|    PySpark|
|Arjun|      Azure|
|Arjun|     Python|
+-----+-----------+

---

# PART 17 — Sales Analysis

Using sales.csv.

Exercise 49  
Calculate total sales.

Exercise 50  
Find total sales per employee.

Exercise 51  
Find best performing employee.

Exercise 52  
Find total sales per product.

---

In [110]:
df_sales.show()

+-------+------+--------+------+
|sale_id|emp_id| product|amount|
+-------+------+--------+------+
|      1|     1|  Laptop| 75000|
|      2|     2|   Mouse|  1500|
|      3|     3|Keyboard|  3000|
|      4|     1| Monitor| 12000|
|      5|     4|  Laptop| 75000|
|      6|     3|   Mouse|  1000|
|      7|     5|Keyboard|  1500|
|      8|     1|  Laptop| 75000|
+-------+------+--------+------+

In [111]:
df_sales.count()

8

In [112]:
df_sales.groupBy(df_sales.emp_id).agg(sum("amount").alias("total_sales")).show()

+------+-----------+
|emp_id|total_sales|
+------+-----------+
|     1|     162000|
|     3|       4000|
|     5|       1500|
|     4|      75000|
|     2|       1500|
+------+-----------+

In [114]:
df_sales.groupBy(df_sales.emp_id).agg(sum("amount").alias("total_sales")).sort(sum("amount").alias("total_sales").desc()).show(1)

+------+-----------+
|emp_id|total_sales|
+------+-----------+
|     1|     162000|
+------+-----------+
only showing top 1 row

In [115]:
df_sales.groupBy(df_sales.product).agg(sum("amount").alias("total_sales")).show()

+--------+-----------+
| product|total_sales|
+--------+-----------+
|  Laptop|     225000|
|   Mouse|       2500|
|Keyboard|       4500|
| Monitor|      12000|
+--------+-----------+

---

# PART 18 — Applying Functions

Create a custom function that categorizes sales:

> 50000 → Premium  
20000–50000 → Medium  
< 20000 → Small  

Exercise 53  
Apply this function to create sale_category.

---

In [116]:
from pyspark.sql.functions import udf
from pyspark.sql.types import StringType
def sales_category(amount):
    if amount>50000:
        return "Premium"
    elif amount>20000:
        return "Medium"
    else:
        return "Small"

udf_sales_category=udf(sales_category,StringType())
df_sales.withColumn("sale_category",udf_sales_category(df_sales.amount)).show()

+-------+------+--------+------+-------------+
|sale_id|emp_id| product|amount|sale_category|
+-------+------+--------+------+-------------+
|      1|     1|  Laptop| 75000|      Premium|
|      2|     2|   Mouse|  1500|        Small|
|      3|     3|Keyboard|  3000|        Small|
|      4|     1| Monitor| 12000|        Small|
|      5|     4|  Laptop| 75000|      Premium|
|      6|     3|   Mouse|  1000|        Small|
|      7|     5|Keyboard|  1500|        Small|
|      8|     1|  Laptop| 75000|      Premium|
+-------+------+--------+------+-------------+

---

# PART 19 — Pandas Comparison

Exercise 54  
Convert Spark DataFrame to Pandas.

Exercise 55  
Perform salary filtering using Pandas.

---

In [117]:
pandas_df=df_employees.toPandas()
pandas_df

   emp_id   name department  salary joining_date
0       1  Rahul         IT   70000   2023-01-10
1       2  Sneha         HR   60000   2022-11-15
2       3  Arjun         IT   75000   2023-03-01
3       4  Priya    Finance   80000   2022-12-20
4       5  Karan         IT   50000   2023-02-05
5       6  Meera       None   72000   2023-04-10
6       7   Amit         HR   58000   2023-01-18

In [118]:
pandas_df[pandas_df.salary>65000]

   emp_id   name department  salary joining_date
0       1  Rahul         IT   70000   2023-01-10
2       3  Arjun         IT   75000   2023-03-01
3       4  Priya    Finance   80000   2022-12-20
5       6  Meera       None   72000   2023-04-10

---

# PART 20 — Widgets in Colab

Create widgets to filter employees.

Exercise 56  
Create dropdown for department.

Exercise 57  
Create slider for salary.

Exercise 58  
Display employees based on widget values.

---

In [120]:
# Dropdown for department
import ipywidgets as widgets
from IPython.display import display

dept_dropdown = widgets.Dropdown(
    options=["All"] + [row["department"] for row in df_employees.select("department").distinct().collect() if row["department"] is not None],
    description="Department:"
)

# Slider for salary
salary_slider = widgets.IntSlider(
    value=50000,
    min=0,
    max=100000,
    step=1000,
    description="Min Salary:"
)

display(dept_dropdown, salary_slider)

Dropdown(description='Department:', options=('All', 'HR', 'Finance', 'IT'), value='All')

IntSlider(value=50000, description='Min Salary:', max=100000, step=1000)

In [122]:
def filter_employees(dept, salary):
    df = df_employees

    if dept != "All":
        df = df.filter(col("department") == dept)

    df = df.filter(col("salary") >= salary)

    df.show()

In [123]:
widgets.interactive(
    filter_employees,
    dept=dept_dropdown,
    salary=salary_slider
)

interactive(children=(Dropdown(description='Department:', index=2, options=('All', 'HR', 'Finance', 'IT'), val…

---

# Final Mini Project

Using all datasets, generate report:

Top Employee  
Average Salary  
Department Employee Count  
Total Sales  
Best Sales Employee  

Save results to:

final_report.txt

---

In [124]:
top_employee = df_employees.orderBy(col("salary").desc()).first()
avg_salary = df_employees.select(avg("salary")).first()[0]
dept_count = df_employees.groupBy("department").count().collect()
total_sales = df_sales.select(sum("amount")).first()[0]
best_sales_emp = df_sales.groupBy("emp_id").sum("amount").orderBy(col("sum(amount)").desc()).first()

with open("final_report.txt","w") as f:
    f.write("Top Employee: " + str(top_employee) + "\n")
    f.write("Average Salary: " + str(avg_salary) + "\n")
    f.write("Department Count: " + str(dept_count) + "\n")
    f.write("Total Sales: " + str(total_sales) + "\n")
    f.write("Best Sales Employee: " + str(best_sales_emp))